"""Bottleneck detection and causal attribution.

The "why did traffic get worse?" answer is computed from simulation evidence,
not generated by a language model. Each candidate cause contributes a score
derived from actual state (a closure on this segment, a signalised downstream
junction with high waiting, a congested successor implying spillback...), and
the scores are normalised into shares.

This matters: an LLM asked to explain congestion will always produce a fluent
answer, including when it is wrong. Attribution here is reproducible and can be
traced back to the specific inputs that produced it.
"""

from __future__ import annotations

from ..contracts import (
    Bottleneck,
    JunctionType,
    RoadNetwork,
    Scenario,
    SegmentMetric,
    VehicleClass,
)

# A segment must be at least this congested to be considered a bottleneck at all.
SPEED_RATIO_THRESHOLD = 0.62
MIN_VEHICLES = 12


def _severity(metric: SegmentMetric) -> float:
    """0..1 congestion severity blending speed loss, waiting and queueing."""
    speed_loss = 1.0 - metric.speed_ratio
    waiting = min(1.0, metric.mean_waiting_s / 60.0)
    queue = min(1.0, metric.max_queue_m / 150.0)
    return round(min(1.0, 0.55 * speed_loss + 0.25 * waiting + 0.20 * queue), 3)


def find_bottlenecks(
    network: RoadNetwork,
    segment_metrics: list[SegmentMetric],
    scenario: Scenario,
    top_n: int = 8,
) -> list[Bottleneck]:
    """Rank the worst segments and attribute a cause breakdown to each."""
    if not segment_metrics:
        return []

    segments = {s.id: s for s in network.segments}
    junctions = {j.id: j for j in network.junctions}
    metrics_by_id = {m.segment_id: m for m in segment_metrics}

    closed_segments = {c.segment_id for c in scenario.lane_closures}
    obstructed = {o.segment_id: o for o in scenario.obstructions}
    incident_segments = {i.segment_id for i in scenario.incidents}
    two_wheeler_share = scenario.vehicle_mix.get(VehicleClass.MOTORCYCLE.value, 0.0)

    candidates = [
        m for m in segment_metrics
        if m.speed_ratio < SPEED_RATIO_THRESHOLD
        and m.vehicles_seen >= MIN_VEHICLES
        and m.segment_id in segments
    ]
    candidates.sort(key=_severity, reverse=True)

    results: list[Bottleneck] = []
    for rank, metric in enumerate(candidates[:top_n], start=1):
        segment = segments[metric.segment_id]
        downstream_junction = junctions.get(segment.to_junction)

        causes: dict[str, float] = {}

        # 1. Direct capacity removal on this segment.
        if segment.id in closed_segments:
            causes["Lane closure"] = 3.2
        if segment.id in incident_segments:
            causes["Incident blocking lane"] = 2.8
        if segment.id in obstructed:
            causes[f"Obstruction ({obstructed[segment.id].kind})"] = 1.4 + obstructed[segment.id].severity

        # 2. Signal delay at the downstream junction.
        if downstream_junction and downstream_junction.type is JunctionType.SIGNALISED:
            causes["Signal delay"] = 0.9 + 1.6 * min(1.0, metric.mean_waiting_s / 45.0)

        # 3. Spillback: successors are themselves congested, so this segment
        #    cannot discharge regardless of its own capacity.
        if downstream_junction:
            successors = [
                metrics_by_id[e] for e in downstream_junction.outgoing_edges
                if e in metrics_by_id
            ]
            if successors:
                worst_successor = min(s.speed_ratio for s in successors)
                if worst_successor < 0.5:
                    causes["Queue spillback"] = 1.1 + 1.8 * (0.5 - worst_successor)

        # 4. Unsignalised conflict: high-degree junction with no control is a
        #    classic Indian failure mode (everyone edges in, nobody clears).
        if downstream_junction and downstream_junction.type in (
            JunctionType.UNCONTROLLED, JunctionType.PRIORITY
        ) and downstream_junction.degree >= 4:
            causes["Unsignalised junction conflict"] = 0.7 + 0.1 * downstream_junction.degree

        # 5. Demand simply exceeding capacity.
        capacity_pressure = metric.density_veh_km / max(segment.lanes * 55.0, 1.0)
        if capacity_pressure > 0.35:
            causes["Demand exceeds capacity"] = 0.8 + 2.0 * min(1.0, capacity_pressure)
        if scenario.demand_multiplier > 1.05:
            causes["Elevated demand"] = 1.2 * (scenario.demand_multiplier - 1.0) * 3.0

        # 6. Modal composition: heavy two-wheeler filtering raises junction
        #    conflict rates even when link capacity is adequate.
        if two_wheeler_share > 0.3 and metric.mean_waiting_s > 8:
            causes["Two-wheeler density"] = 0.6 + 1.2 * (two_wheeler_share - 0.3)

        if not causes:
            causes["Recurrent congestion"] = 1.0

        total = sum(causes.values())
        shares = {k: round(v / total, 3) for k, v in sorted(
            causes.items(), key=lambda kv: kv[1], reverse=True
        )}

        # Locate the bottleneck at the downstream end, where the queue forms.
        lat = downstream_junction.lat if downstream_junction else 0.0
        lon = downstream_junction.lon if downstream_junction else 0.0
        if not lat and segment.geometry:
            lon, lat = segment.geometry[-1][0], segment.geometry[-1][1]

        results.append(
            Bottleneck(
                rank=rank,
                segment_id=segment.id,
                junction_id=segment.to_junction,
                name=segment.name or f"Segment {segment.id}",
                lat=lat,
                lon=lon,
                severity=_severity(metric),
                speed_ratio=metric.speed_ratio,
                mean_waiting_s=metric.mean_waiting_s,
                queue_m=metric.max_queue_m,
                causes=shares,
            )
        )
    return results


def compare_metrics(baseline, scenario_metrics) -> tuple[dict, dict, str]:
    """Baseline vs scenario deltas, plus a plain-language verdict."""
    fields = [
        "avg_speed_kmh", "avg_travel_time_s", "avg_delay_s", "max_queue_m",
        "throughput_veh_hr", "congestion_index", "vehicles_arrived", "total_co2_kg",
    ]
    deltas: dict[str, float] = {}
    deltas_pct: dict[str, float] = {}
    for field in fields:
        base = float(getattr(baseline, field, 0) or 0)
        new = float(getattr(scenario_metrics, field, 0) or 0)
        deltas[field] = round(new - base, 2)
        deltas_pct[field] = round(((new - base) / base) * 100, 1) if base else 0.0

    speed_change = deltas_pct.get("avg_speed_kmh", 0.0)
    delay_change = deltas_pct.get("avg_delay_s", 0.0)
    if speed_change <= -25:
        verdict = "Severe degradation: the network cannot absorb this scenario."
    elif speed_change <= -10:
        verdict = "Significant degradation in network performance."
    elif speed_change < -2:
        verdict = "Mild degradation; the network largely absorbs this scenario."
    elif speed_change > 10:
        verdict = "Substantial improvement over the baseline."
    elif speed_change > 2:
        verdict = "Modest improvement over the baseline."
    else:
        verdict = "Essentially unchanged from the baseline."
    if delay_change > 50 and speed_change > -10:
        verdict += " Delay rises sharply even though mean speed holds up, indicating localised queueing."
    return deltas, deltas_pct, verdict
